"""Write RESULTS.md: every number the paper cites, with its provenance."""
import json

import pandas as pd

from common import TABLES, EMOTIONS, EMO_NAME

ROOT = TABLES.parents[1]


def pct(x):
    return f"{100 * x:.1f}%"


def main():
    a = json.load(open(TABLES / "label_audit.json"))
    p = json.load(open(TABLES / "perceptual_audit.json"))
    L = []
    w = L.append

    w("# Results\n")
    w("Generated by `src/08_summary.py`. Every figure below comes from the "
      "CREMA-D release; nothing is hand-entered.\n")

    w("## 1. Does a listener recover the actor's instruction?\n")
    w(f"Voice-only condition, {a['n_ratings']:,} ratings over {a['n_clips']} "
      f"clips ({a['mean_raters_per_clip']:.1f} raters per clip, "
      f"{a['n_actors']} actors).\n")
    w("| Tie convention | Recovery |")
    w("|---|---|")
    names = {
        "unambiguous_only": "unambiguous plurality only (**reported**)",
        "tie_counts_as_miss": "tie counts as a miss",
        "tie_broken_by_intensity": "tie broken by rated intensity",
        "tie_broken_at_random": "tie broken at random",
        "tie_counts_as_hit": "tie counts as a hit",
        "mean_vote_mass_on_intended": "mean vote mass on the intended label",
    }
    for k, label in names.items():
        w(f"| {label} | {pct(a['recovery'][k])} |")
    w(f"| _chance (uniform)_ | 16.7% |")
    w("")
    r = p["raw_recount"]
    w(f"Recomputing from the raw response file, which carries "
      f"{r['extra_vs_shipped']:,} ratings the shipped aggregation drops: "
      f"{pct(r['recovery_unambiguous'])} overall, "
      f"{pct(r['sad_recovery'])} for sad.\n")

    w("### Per intended category\n")
    w("| Intended | n | Recovery | Agreement | Entropy |")
    w("|---|---|---|---|---|")
    for e in EMOTIONS:
        d = a["per_emotion"][e]
        w(f"| {EMO_NAME[e]} | {d['n']} | {pct(d['unambiguous_only'])} | "
          f"{d['mean_agreement']:.2f} | {d['mean_entropy']:.2f} |")
    w("")

    w("## 2. Where the labels go\n")
    na = p["neutral_attractor"]
    w(f"- Non-neutral instructions heard as neutral: "
      f"**{pct(na['nonneutral_intent_heard_as_neutral'])}**")
    w(f"- Sad-intended clips heard as neutral: "
      f"**{pct(na['sad_heard_as_neutral'])}**")
    w(f"- Perceived label is neutral for {pct(na['perceived_neutral_share'])} "
      f"of the corpus; intended, {pct(na['intended_neutral_share'])}\n")

    w("## 3. Reliability and ceilings\n")
    rel, hc = p["reliability"], p["human_ceiling"]
    w(f"- Fleiss' kappa {rel['fleiss_kappa_perceived']:.3f}, "
      f"Krippendorff's alpha {rel['krippendorff_alpha_perceived']:.3f}")
    w(f"- Two listeners on the same clip agree "
      f"{pct(rel['rater_rater_agreement'])} of the time")
    w(f"- Leave-one-rater-out: a listener matches the actor "
      f"**{pct(hc['rater_vs_intended'])}**, their peers "
      f"**{pct(hc['rater_vs_peer_plurality'])}** "
      f"({hc['n_ratings_scored']:,} ratings scored)\n")

    w("### By presentation modality and acted intensity\n")
    w("| Condition | Recovery |")
    w("|---|---|")
    for k, v in p["by_modality"].items():
        w(f"| {k} | {pct(v['recovery_unambiguous'])} |")
    for k in ["LO", "MD", "HI"]:
        if k in p["by_intensity"]:
            w(f"| intensity {k} | {pct(p['by_intensity'][k]['recovery'])} |")
    w("")

    res_path = TABLES / "main_results.csv"
    if res_path.exists():
        res = pd.read_csv(res_path)
        w("## 4. Systems\n")
        w("Speaker-independent 5-fold CV over 91 actors; class-balanced "
          "training in every regime. UAR in %.\n")
        w("| System | Trained on | UAR vs intended | UAR vs perceived | "
          "WA vs intended | WA vs perceived | R |")
        w("|---|---|---|---|---|---|---|")
        for _, r in res.sort_values(["system", "train"]).iterrows():
            w(f"| {r.system} | {r.train} | {100*r.UAR_intended:.1f} | "
              f"{100*r.UAR_perceived:.1f} | {100*r.WA_intended:.1f} | "
              f"{100*r.WA_perceived:.1f} | {100*r.rater_agreement:.1f} |")
        w("")

    rk_path = TABLES / "ranking_analysis.json"
    if rk_path.exists():
        rk = json.load(open(rk_path))["ranking"]
        w("## 5. Does the answer key change the ranking?\n")
        for regime in ["intended", "perceived", "soft"]:
            if regime not in rk:
                continue
            d = rk[regime]
            w(f"- Systems trained on **{regime}**: Kendall tau = "
              f"{d['kendall_tau']:.3f}, {d['n_inversions']}/{d['n_pairs']} "
              f"pairs invert ({d['n_significant_inversions']} with both "
              f"differences significant)")
        if "pooled" in rk:
            d = rk["pooled"]
            w(f"- **Pooled leaderboard** ({d['n_entries']} entries, i.e. every "
              f"system x training label): Kendall tau = "
              f"{d['kendall_tau']:.3f}, {d['n_inversions']}/{d['n_pairs']} "
              f"pairs invert")
            w(f"  - best under intended: `{'/'.join(d['top_intended'])}` "
              f"-> rank {d['rank_of_intended_winner_under_perceived']} under "
              f"perceived")
            w(f"  - best under perceived: `{'/'.join(d['top_perceived'])}` "
              f"-> rank {d['rank_of_perceived_winner_under_intended']} under "
              f"intended")
        w("")

    (ROOT / "RESULTS.md").write_text("\n".join(L) + "\n", newline="\n")
    print("wrote", ROOT / "RESULTS.md")


if __name__ == "__main__":
    main()
